import discord
from discord.ext import commands
import random
import time
from datetime import datetime, timedelta
from pytz import timezone
import pytz
import sys

format = " %H : %M : %S "

#now_utc = datetime.now(timezone('UTC'))
#now_europe = now_utc.astimezone(timezone('europe/berlin'))
tz = pytz.timezone('Europe/Berlin')
count = 1
client = commands.Bot(command_prefix = '.')

@client.event
async def on_ready():
    print("I am alive.")

@client.event
async def on_member_join(member):
    print(f'(member) has joined the server!')

@client.event
async def on_member_remover(member):
    print(f'(member) has left the server!')

@client.command(aliases=['timelondon'])
async def _UTCtime(ctx):

        await ctx.send(f"Omg the time is " + (time.strftime("%H""h:""%M""m:""%S""s""!!! :pray:"))),  

@client.command(aliases=['timelondonloop'])
async def _UTCtime1(ctx):
    var1 = 1 
    while var1 < 21:
        var1 = var1 + 2
        time.sleep(10)
        await ctx.send(f"Omg the time is " + (time.strftime("%H""h:""%M""m:""%S""s""!!! :pray:"))),     

@client.command(aliases=['kiangetback'])
async def _kianisatwat(ctx):
    var1 = 1 
    while var1 < 6969:
        var1 = var1 + 1
        time.sleep(2)
        await ctx.send(f"@Sargent Chaddy Boi oi!"),     

@client.command(aliases=['timeberlin'])
async def _UTChitler(ctx):
    var2 = 1 
    while var2 < 2:
        var2 = var2 + 2
        time.sleep(1)
        await ctx.send(f"Omg the time is " + (datetime.now(tz).strftime("%H:%M:%S!!! \n:pray:"))),   

@client.command(aliases=['ping'])
async def _ping(ctx):
    await ctx.send(f'My ping is {round(client.latency * 1000)}ms')

@client.command(aliases=['die'])
async def _die(ctx):
    await sys.exit("Bot closed by Discord User")

@client.command(aliases=['name'])
async def _same(ctx):
    var2 = 1 
    while var2 < 10000:
        var2 = var2 + 1
        time.sleep(1)
        responses = responses = ["listen","advice","feed","offer","whale","giant","planned","hold","copper"
"truck","spent","practice","influence","sent","cotton","vegetable","because","gone","field","create","diagram","pencil","provide","hard","swam","lead","cause","serious","cup","speech","said","spoken","running","structure","science","bet","thumb","settle","guard","vessels","adult","roof","great","western","constantly","crop","replied","tool","spread","health","remain","easily","put","plastic","job","wish","contrast","busy","sheep","finger","push","object","pony","raw","depth","difficulty","act","clean","consider","flat","direction","ground","rate","did","handle","jungle","farm","making","opposite","wooden","sister","orbit","bark","cave","pair","difficult","duck","balloon","apart","habit","roll","seeing","deal","feet","express","accept","bottom","dear","indicate","rising","were","every","or","industrial","till","probably","rhyme"
"bill","gently","left","shallow","cent","grass","mice","forth","accident","biggest","office","bound","noon","all","produce","different","office","has","rice","union","occasionally","than","interior","word","fly","alive","mill","discussion","toy","wheat","rising","tin","specific","offer","spite","report","seeing","amount","source","row","list","grain","angle","organized","combination","tail","dirty","variety","topic","extra","crowd","gulf","speak","gate","shells","additional","leaving","baseball","small","station","tea","short","vowel","today","unit","variety","original","better","again","in","low","pond","guess","shelf","very","other","gave","apartment","child","curious","pole","lay","continent","tongue","tax","dozen","wire","service","make","hungry","art","me","appearance","cloud","hope","receive","mass","sick"
"ride","pleasant","stuck","under","take","animal","course","form","him","honor","with","couple","aware","wash","we","scientist","leave","matter","closer","shorter","understanding","them","season","object","shop","cup","use","necessary","blow","primitive","broken","dear","solar","brought","noise","walk","famous","page","walk","caught","breath","remove","husband","enemy","prevent","prepare","amount","handle","except","farm","easier","measure","owner","lovely","noise","sheep","pilot","such","cool","coffee","expression","hold","earn","lose","report","nuts","loss","second","may","milk","route","make","unit","we","gray","continued","story","climate","slip","mission","hurry","system","discover","feathers","struggle","someone","throw","exchange","crowd","hard","am","dollar","most","shallow","dark","appropriate","eager","environment"
"separate","trail","saddle","leader","poetry","hot","took","observe","where","transportation","pony","planning","threw","fire","anyone","steep","ought","imagine","twelve","shot","observe","nose","cost","cause","manufacturing","report","ground","best","shells","twice","police","hello","exact","soft","particularly","however","sheep","phrase","wait","those","tank","began","moment","city","source","nine","dinner","alive","perfect","happily","our","brief","piece","small","expression","however","movie","oil","manner","tobacco","matter","you","tank","glad","coach","happy","seems","grew","compass","doctor","lift","hunt","tide","mean","high","verb","rock","blind","steep","machinery","smell","program","touch","construction","chicken","combine","government","program","shelf","experience","putting","doubt","wonder","direction","examine","manufacturing","wire","motor"
"purpose","eager","up","manner","since","common","ready","magnet","addition","square","college","whose","probably","refused","unknown","attention","shirt","difference","each","pencil","unless","central","greatly","was","piece","given","character","saddle","noise","mental","needed","independent","thumb","heavy","fox","coach","mice","carried","act","you","composed","whistle","grandmother","arrive","prevent","mouth","frog","importance","measure","during","salt","grass","into","high","curious","poor","decide","hang","high","being","member","flame","birth","only","slope","else","moment","sentence","driver","sun","reader","chamber","syllable","new","far","firm","minerals","burst","society","feet","tales","send","quarter","may","lady","soft","huge","cool","science","hello","circle","solid","alike","group","underline","dozen","fat","stone"
"where","rapidly","zoo","empty","gradually","among","primitive","melted","figure","social","gentle","stick","sleep","sound","sometime","classroom","talk","different","shallow","citizen","ants","cook","eight","steady","president","regular","classroom","search","up","elephant","practice","trap","fur","personal","greater","stranger","weak","equator","all","plant","final","poetry","take","bend","air","grew","man","government","spent","might","clothing","fruit","well","anyway","pot","speed","six","base","should","pound","blood","forgot","underline","center","drive","graph","into","garden","verb","once","spirit","wonderful","cat","mean","variety","day","office","couple","health","learn","bean","too","term","exciting","sound","came","cannot","post","substance","might","series","route","policeman","spell","show","common","angry","having"
"military","chemical","compass","agree","automobile","know","control","lion","national","younger","burst","cat","question","made","outer","quiet","excellent","trick","pour","west","discussion","check","divide","nearest","who","lunch","has","service","her","design","series","molecular","though","pattern","slow","writer","tongue","quite","nearest","tales","extra","image","troops","warm","catch","by","opportunity","hot","chain","entire","thick","bite","start","drive","sell","enough","hot","opposite","supply","shore","knife","quarter","mix","story","various","community","mail","push","neck","influence","during","exercise","wire","dig","learn","court","show","lack","score","plan","fighting","pole","bright","halfway","jungle","off","meat","treated","snake","settle","earth","root","thirty","fog","same","wait","consist","there"
"center","correct","its","engine","underline","happened","browserling","thank","however","wealth","harbor","headed","go","fill","saddle","through","mysterious","review","thy","know","lying","gravity","view","outline","traffic","merely","period","correctly","setting","forth","farm","too","material","kind","planned","terrible","skill","needs","policeman","size","cry","clock","pick","ordinary","himself","operation","across","alphabet","come","then","put","while","record","bill","root","hurry","him","known","coming","how","cheese","flies","cross","better","raw","gentle","equal","sand","handsome","with","no","sang","mice","entire","fifteen","goose","off","wherever","selection","saddle","worse","total","make","mice","write","say","thick","come","closely","happily","symbol","experience","basic","page","because","valley","planet","beauty"
"correctly","tea","three","how","upper","discuss","club","book","account","never","eaten","mean","limited","twice","too","nation","grandfather","something","stopped","planned","hair","surface","mostly","excellent","course","community","before","whale","rice","pond","knew","important","border","hello","boy","too","underline","forgotten","shore","salt","today","master","castle","bus","spirit","quickly","support","steam","brush","pride","actually","enough","blow","various","doubt","smaller","tried","him","mill","now","all","surface","firm","lake","writing","brief","primitive","smooth","accident","bat","name","available","observe","fear","strange","written","bigger","body","type","copy","size","town","slipped","answer","verb","topic","jump","lose","brought","subject","build","tea","shown","sat","alone","putting","fact","on"
"deep","visit","market","maybe","column","hit","gold","city","from","discussion","city","stove","steam","travel","smoke","zoo","electricity","friendly","method","mix","sum","nearby","key","travel","as","compare","positive","concerned","nearer","mostly","pound","rhythm","living","rocket","orbit","syllable","depend","because","oil","grade","outline","report","compass","branch","ground","one","bar","check","doll","thumb","spoken","farther","leaving","completely","wall","wing","screen","worried","strike","southern","tall","leaving","plane","clean","tiny","human","detail","better","review","you","corner","atmosphere","swam","struggle","wear","noted","below","month","browserling","operation","specific","among","kitchen","coach","stood","safety","expression","eaten","coast","second","reach","test","anywhere","flower","eight","industry","bare","met"
"strange","attack","older","rhythm","magic","nobody","through","peace","ants","flies","typical","sheet","youth","water","cage","whom","rising","hot","lot","determine","ordinary","curve","proper","beginning","crop","salmon","live","chicken","coming","nodded","largest","establish","rule","thought","foreign","rocky","like","claws","stared","make","solid","quietly","fairly","excellent","breathing","wheel","jungle","discussion","bigger","she","dress","courage","oxygen","fallen","sweet","instead","audience","guide","well","shoulder","root","combination","add","period","sea","oil","automobile","hall","hot","someone","onto","slept","four","vertical","else","attack","classroom","flame","use","dear","there","scientist","beyond","nails","yard","unless","carefully","accurate","place","pet","ought","supper","slight","slope","moment","driving","pleasure","income"
"thought","tribe","route","firm","cake","leaving","hill","pen","specific","rays","after","sum","threw","composition","mathematics","melted","like","rock","mostly","believed","basis","crew","private","hundred","chair","part","corn","joined","range","thank","discuss","ring","negative","round","down","sets","brave","coat","nature","history","whether","fighting","off","business","supper","eager","burn","special","location","must","ants","either","studied","camera","home","special","land","sit","away","eaten","separate","thing","actual","rocky","mail","feed","angry","mental","told","composed","her","meat","dull","rabbit","whenever","volume","break","against","worse","compound","clean","valuable","entire","collect","spite","equipment","curious","trunk","fox","treated","object","disappear","bridge","subject","explanation","giant","underline","stove"
"club","hidden","count","golden","engine","stand","fox","leg","oxygen","pony","soil","cool","frequently","chicken","further","along","difficult","opinion","deal","journey","nuts","leg","pick","fairly","them","lonely","sink","along","structure","weak","recall","plates","valuable","something","play","greatest","notice","surrounded","cotton","coast","minerals","second","he","against","went","indeed","memory","attention","since","itself","nine","sold","them","account","declared","nose","happily","help","huge","search","swept","see","large","structure","deeply","longer","escape","swung","huge","wife","manufacturing","sit","favorite","raw","baby","easily","forgotten","bowl","press","if","heavy","diagram","atomic","in","verb","ancient","hole","ready","worse","fast","all","toy","means","scared","universe","anywhere","difficult","disease"
"region","studied","every","average","at","sunlight","everybody","since","gentle","dig","plan","board","garage","bent","for","variety","space","income","balloon","feet","front","six","such","storm","final","television","tales","hello","fruit","faster","rather","tall","fly","prepare","told","wore","universe","percent","parts","spider","appropriate","mine","grew","glass","roar","part","at","structure","smoke","stronger","steady","jar","stove","shown","system","route","tail","write","laid","additional","afternoon","torn","knowledge","tales","third","bush","diameter","straw","hair","locate","shoe","nest","beneath","especially","also","belt","advice","tube","box","seen","foreign","shadow","slipped","tight","also","four","stage","none","me","waste","stove","structure","high","coming","railroad","does","fight","judge"
"cheese","equally","tube","through","wish","event","all","writing","arrange","difficult","school","garage","toward","review","firm","collect","passage","sound","frozen","mood","leather","wave","excitement","rhythm","failed","chief","scientist","bare","symbol","apple","needed","little","worker","slabs","made","queen","browserling","beginning","farther","industry","given","close","pale","tribe","corn","hand","speed","eager","wave","pony","phrase","board","claws","talk","sky","block","disease","account","plastic","herd","bee","body","baby","forest","jet","triangle","guess","from","because","include","piano","road","cut","because","string","upon","few","negative","ate","oxygen","night","show","cool","attention","wealth","against","dug","went","gold","outer","national","exercise","straw","dear","post","girl","fat","lead"
"does","farm","contrast","sign","proud","forget","went","pull","play","small","contain","plant","seen","spend","seldom","folks","she","many","quick","pink","lose","prove","difference","accident","mice","composition","north","feet","behind","divide","private","browserling","real","sang","understanding","fact","grown","shut","everyone","beauty","solid","solid","silent","hand","moving","ourselves","source","lonely","fairly","coffee","aware","soldier","happy","complete","putting","bread","rays","highway","hearing","whale","lips","native","giant","upon","refused","pure","smooth","flag","loud","quickly","drink","tales","cage","dream","question","express","came","date","bicycle","garden","consider","ask","saw","swung","beautiful","wrapped","describe","they","toy","purple","corn","football","trail","matter","glad","harbor","wide","coffee"
"sky","library","piece","climate","be","team","spoken","leg","lesson","surprise","piano","composition","including","become","customs","tip","dropped","instrument","directly","correctly","number","got","smell","shall","weak","between","kill","meet","has","those","should","creature","made","team","smooth","are","slabs","on","member","win","alone","none","needed","health","border","sang","partly","nodded","fruit","newspaper","as","farm","sometime","differ","hearing","curve","of","explain","ready","religious","remember","lay","species","toward","glass","grandfather","pie","additional","result","alike","curve","customs","situation","think","yard","late","promised","huge","business","topic","settlers","lovely","hurry","seems","rising","short","lunch","entire","great","buy","by","invented","choose","forty","phrase","where","planned","western"
"lovely","judge","room","each","anyway","sail","cutting","labor","closely","cloud","engineer","deep","meet","joy","coffee","field","worried","nothing","funny","sold","calm","promised","hole","supper","value","location","degree","handsome","tube","winter","suppose","buried","obtain","dangerous","horse","copy","your","grandmother","think","last","answer","lesson","trouble","fierce","growth","passage","previous","hold","printed","gentle","neighborhood","force","key","believed","shape","lips","ear","massage","harder","except","silk","plenty","quite","tribe","term","slide","somebody","thing","fighting","why","laid","rays","station","shallow","butter","run","birth","push","fought","jump","bush","future","quietly","skill","recognize","sheet","thread","thick","trick","thy","dirty","clear","locate","job","announced","stone","fifth","or"
"oil","industry","cover","mad","stems","basis","goes","maybe","balance","recognize","court","pine","plant","shorter","rock","hello","tank","herself","nobody","wait","bell","claws","noted","brief","shelf","letter","aloud","promised","fat","prove","block","matter","strength","part","percent","best","satellites","way","down","medicine","mental","simply","play","period","play","milk","without","south","street","child","community","understanding","sing","organization","heart","figure","correct","truth","underline","blind","weight","cup","dance","boat","milk","bad","mix","sort","automobile","open","leather","busy","doctor","somebody","down","press","syllable","radio","coffee","drew","thou","lift","bowl","only","spend","cup","letter","our","perfect","record","soap","respect","wave","summer","avoid","hunter","social","answer"
"ants","straw","high","nearest","garden","flat","us","ground","everywhere","shorter","skill","shelf","trail","discover","trouble","principal","adjective","cry","taken","nails","drew","breeze","green","below","sets","design","frozen","limited","return","tie","start","meet","valuable","felt","drive","scene","young","become","voice","cowboy","eye","shells","fierce","draw","hide","sudden","palace","forth","branch","prevent","threw","example","even","bowl","putting","earth","tin","short","both","lion","change","corn","face","hidden","laugh","author","wore","worth","choice","sunlight","sang","hurry","jar","arrangement","birthday","funny","development","military","for","boat","ought","bring","pilot","kill","tall","inch","progress","written","hung","rocket","size","child","ready","rays","mine","hidden","snow","busy"
"sing","such","ate","flame","dozen","stove","habit","sight","sign","greatest","has","period","knowledge","job","alone","strength","shall","curious","neck","machinery","vessels","human","loss","stems","service","special","important","introduced","aid","fuel","this","pair","sit","teeth","chance","amount","region","pitch","catch","television","married","little","world","exact","since","wagon","mix","aboard","ice","hold","two","report","single","outside","zoo","troops","dull","dull","week","fewer","ship","morning","heard","bent","mean","stems","lady","stairs","potatoes","fun","table","eager","valuable","pound","potatoes","properly","jet","heat","gas","given","orbit","old","series","treated","crew","shadow","mountain","ought","wrapped","war","reader","introduced","factor","discover","report","cutting","increase","name"
"heard","vessels","later","disappear","pure","third","earth","brass","cowboy","slide","fully","brother","tower","next","home","stood","few","wooden","sang","coal","second","purpose","held","mathematics","quite","go","label","stomach","rule","live","seems","muscle","planned","master","common","know","particular","whale","depth","former","dress","meal","able","whole","conversation","whatever","telephone","wire","difference","truth","jar","heat","object","knife","chosen","again","hardly","spell","alphabet","sport","ground","product","answer","swimming","wolf","may","respect","word","serve","jet","flight","buy","fort","seed","steep","research","tobacco","gravity","bring","give","grown","stepped","hidden","forty","warn","beauty","corner","asleep","label","newspaper","cutting","whispered","silent","swing","talk","supply","tiny","lake"
"peace","place","nails","proud","wise","bank","consonant","family","tears","game","actually","spread","surface","though","rough","meat","becoming","swing","list","slowly","influence","realize","today","rather","graph","division","won","arm","variety","introduced","shot","garage","may","mile","chief","gradually","lucky","whose","news","series","movie","daily","depth","different","get","one","partly","parent","honor","canal","feature","herd","spirit","surface","term","end","ball","saved","greatest","automobile","control","failed","grandmother","else","describe","dollar","while","light","outline","summer","pale","grandfather","sport","lips","key","fierce","opposite","pressure","political","before","least","notice","fuel","move","needed","die","you","eye","lungs","sing","promised","whatever","door","lamp","believed","curve","source","day"
"science","decide","lake","long","shut","scared","take","sign","blew","express","waste","island","ran","gradually","common","front","drove","board","carried","improve","his","largest","note","require","pole","bent","layers","wooden","straw","chamber","perfectly","central","bank","street","had","hollow","condition","physical","program","shaking","voyage","research","mud","sudden","rapidly","ship","climate","breathing","pleasant","prize","leg","chief","volume","shadow","hollow","cook","worker","maybe","bean","wonder","body","excitement","brother","lot","silent","structure","cow","memory","farther","wool","cat","meat","stay","jar","fourth","worse","rear","correctly","manufacturing","seen","level","sunlight","soil","seeing","outline","characteristic","mountain","nodded","lost","buffalo","drawn","youth","major","balance","needed","fastened","location","hung"
"ocean","radio","aware","aboard","hold","problem","ancient","exercise","actually","spite","jack","express","think","real","poor","teach","lovely","loss","load","drove","gun","announced","shade","structure","mother","close","wire","simple","property","deer","want","soldier","under","top","ahead","orange","sitting","us","few","buried","structure","torn","day","goose","first","stop","around","recently","combine","use","case","army","title","pond","fall","pilot","replied","there","heavy","throat","track","stomach","organized","my","biggest","few","diagram","business","definition","clearly","mean","soft","with","elephant","scientist","dirt","load","sink","edge","mental","he","smile","frequently","these","daily","universe","concerned","they","breakfast","spent","choose","welcome","contrast","idea","writer","know","date","conversation"
"very","rose","selection","meet","weight","principle","egg","field","joined","running","develop","hollow","those","practical","blood","rear","merely","sum","salt","minute","neck","advice","produce","earlier","bet","city","hit","help","morning","plan","beneath","service","force","curious","exact","key","running","save","realize","wonder","child","directly","write","settlers","nearest","zoo","seeing","strength","explore","hungry","folks","public","handle","draw","everyone","mile","bow","had","eleven","border","hat","pan","struggle","search","valley","it","concerned","though","apartment","everybody","cause","salmon","square","joy","because","film","breathing","crop","tube","see","rays","behavior","thought","but","see","scene","smaller","page","soon","poem","park","equipment","too","act","cut","energy","equally","mental"
"worth","occasionally","us","worth","indeed","water","strength","circle","student","yesterday","average","leader","rod","making","get","wrapped","physical","same","test","alphabet","mainly","will","typical","aware","worried","increase","tonight","pure","prove","experiment","mad","cap","bill","port","leather","straight","chamber","naturally","oxygen","visit","straw","lips","beat","dream","anywhere","addition","bad","entirely","rocket","create","mass","pink","someone","steam","gasoline","known","earlier","send","warn","sky","watch","airplane","goes","object","allow","these","therefore","dirt","race","hide","lesson","political","door","population","mistake","tower","fell","recognize","worse","invented","both","steady","fully","realize","joined","pupil","jack","hundred","led","hand","roar","attention","army","shown","better","middle","company","write"
"recognize","control","stems","either","gone","tobacco","only","sad","crowd","state","test","ranch","nearest","establish","local","tube","officer","pink","frame","arrive","blew","baseball","leather","group","influence","pen","slabs","buy","experiment","face","box","no","hay","whole","duty","substance","pan","stay","tank","decide","burn","opposite","riding","against","proper","cream","bone","become","proper","route","structure","situation","eleven","window","all","surface","material","lot","becoming","still","cross","itself","daily","pleasure","floor","supply","support","gradually","equipment","went","already","terrible","get","street","trunk","pain","yes","flower","older","nest","moon","onto","surrounded","swam","goose","tip","refused","would","give","firm","song","bee","whistle","eye","either","buy","result","plates"
"simplest","experience","hay","nuts","south","another","heading","cause","note","contrast","else","all","lunch","key","neighbor","exciting","care","laid","goes","thought","main","town","scientist","better","date","married","she","ready","development","necessary","us","determine","shop","smell","will","please","nothing","kill","guess","native","tried","five","shall","ran","away","pipe","giant","how","hill","sense","expect","gently","size","headed","see","mail","position","got","expect","tin","although","shut","morning","circle","give","should","sky","police","go","may","had","owner","edge","warm","sit","reason","further","therefore","include","breath","pour","stage","beside","explore","sentence","duty","ourselves","order","boy","garden","customs","simplest","fairly","cross","four","fully","swam","meat"
"poetry","thin","sunlight","rays","enough","while","root","fed","suddenly","medicine","suit","one","new","direction","origin","involved","thirty","muscle","shoulder","sing","alphabet","physical","stiff","everything","along","though","realize","bound","extra","mill","bent","wrapped","noted","path","field","newspaper","driving","beyond","own","division","globe","east","camera","actually","donkey","date","heading","solve","frog","forgotten","tool","allow","realize","medicine","off","afraid","deep","breeze","organized","biggest","perfect","famous","happy","went","add","parent","general","grown","motion","nest","store","nice","course","law","talk","knew","me","worried","situation","village","within","there","greatest","company","corn","blank","piece","cream","particularly","ago","important","expression","fur","nearly","give","whether","very","women"
"hungry","gift","death","refer","probably","buy","percent","account","flame","few","my","anything","bring","collect","what","fed","sister","slope","became","carry","evidence","angle","audience","sink","square","wherever","current","selection","indicate","anyone","form","problem","west","flies","weak","excellent","good","off","finish","see","importance","physical","show","alike","date","fresh","will","too","apple","buried","floating","trouble","egg","maybe","perfect","chest","small","bar","glad","trouble","vowel","write","alive","cold","line","satellites","type","nor","after","anywhere","iron","offer","minerals","solution","throw","proper","chart","sheet","known","anything","day","changing","doubt","on","command","something","deal","gasoline","still","pitch","fish","feed","jar","provide","movie","whose","method","production"
"rather","blanket","felt","taken","clear","beautiful","all","milk","two","muscle","horse","mathematics","stopped","felt","indicate","cent","major","car","exciting","to","once","flower","gently","able","whatever","gas","copper","hay","highway","give","studied","additional","straight","goes","garage","mouth","cross","skin","steep","exercise","medicine","sunlight","shot","lucky","ranch","flat","block","increase","fed","month","forget","merely","troops","chest","our","lovely","none","cloth","respect","rhyme","reason","warm","only","men","there","bat","although","solution","chain","system","test","together","war","yes","outline","broke","sleep","cream","captain","hurt","ocean","clothes","spirit","high","bound","valley","heat","bus","shinning","shallow","perfect","blood","fellow","cotton","student","folks","being","forest"
"sheet","duty","fire","him","maybe","personal","breath","respect","success","degree","chest","drew","fourth","born","against","spread","popular","needs","seven","ability","canal","heavy","fire","agree","middle","dog","clearly","sign","mine","determine","garden","partly","magnet","nodded","roll","pony","until","silk","low","themselves","leader","success","let","store","sand","character","continent","dawn","two","her","moon","gate","dream","later","remarkable","outline","pressure","headed","held","seems","construction","given","army","court","officer","ourselves","too","itself","easy","goose","library","visit","hurry","touch","buried","wire","invented","lot","practice","tone","zero","during","late","anything","worry","nodded","farm","thing","sat","fresh","off","quietly","case","escape","massage","acres","breathe","promised"
"day","accept","satisfied","breathe","welcome","student","ground","opposite","subject","equally","trap","possibly","lady","swept","statement","service","silly","youth","either","detail","policeman","fully","customs","written","two","master","source","step","been","nuts","bet","help","away","personal","lot","larger","bell","belong","might","divide","choice","dirt","graph","party","she","down","outer","goose","settle","atom","eager","angry","shall","chose","dozen","torn","melted","surrounded","gray","hold","month","slide","without","screen","sudden","carefully","invented","sweet","pan","my","wide","enter","speed","properly","naturally","enjoy","carry","hurried","treated","worse","planet","except","grain","cattle","chair","different","handle","will","lamp","eat","carried","cutting","matter","near","earn","chief","around","on"
"not","without","dug","pour","wrote","west","be","order","cookies","leg","command","finally","everyone","supply","plenty","become","knowledge","gravity","picture","taught","market","officer","thus","stranger","mill","atom","coffee","hang","prize","instead","bite","solar","eat","two","manner","railroad","rapidly","corn","traffic","triangle","box","history","gun","glad","hole","mix","involved","knife","opinion","call","gentle","explore","song","feed","recent","outside","difference","different","terrible","your","tell","fog","fact","ride","grandmother","yard","coat","proper","possible","cut","parallel","definition","leaving","clay","degree","push","there","ride","wrapped","burn","statement","furniture","broke","announced","opposite","probably","western","brush","younger","perfect","road","worth","policeman","building","attack","light","once","shoulder"
"have","office","rice","nature","idea","simple","ants","experiment","drink","brother","did","standard","discovery","community","muscle","herd","high","south","balance","have","letter","pot","ranch","distant","rain","orbit","remarkable","nodded","man","parallel","merely","rabbit","each","buffalo","wing","everything","honor","century","report","anyone","only","dance","information","speak","trace","early","stomach","free","relationship","jump","shade","exact","pure","explore","parallel","too","finally","would","came","habit","eight","teacher","hurried","lift","visit","orbit","cut","older","left","yellow","rain","comfortable","bee","zoo","save","key","tower","radio","warm","white","base","grade","ready","particular","object","wagon","arrangement","popular","mathematics","tired","voyage","party","hunter","capital","daily","pet","angry","sea"
"trick","draw","examine","industry","citizen","changing","using","began","stuck","winter","morning","disappear","tell","related","major","likely","rather","trip","supper","brother","using","audience","roof","basket","influence","somebody","complete","grabbed","whale","whale","different","direction","ready","thirty","wealth","selection","told","about","social","serious","century","swimming","double","office","trace","care","idea","wagon","frozen","shall","meal","visitor","flight","pick","surface","evidence","film","exactly","quarter","family","tree","near","ready","door","industry","army","until","grass","wing","dress","vessels","function","tide","wind","object","collect","college","plates","bean","powerful","shelf","small","west","rain","attention","label","apart","color","quiet","since","term","fifteen","pile","beneath","compare","adult","clear","freedom"
"world","birthday","sale","check","state","standard","sheep","slope","root","nest","tongue","enough","board","rocket","refused","mixture","breath","original","happened","you","another","pipe","of","drove","owner","mostly","president","send","somehow","almost","clothes","burn","terrible","outside","question","tired","proud","needs","donkey","beginning","name","move","smoke","be","gradually","primitive","country","said","black","me","met","pocket","canal","machinery","power","met","horse","felt","mile","home","may","led","several","cake","around","his","decide","telephone","browserling","cutting","stage","lack","flower","fall","doll","earlier","stomach","cowboy","plain","press","apartment","art","basis","satisfied","against","child","powder","tight","lucky","realize","worker","basket","dinner","hearing","hall","though","other","examine"
"task","income","young","week","recently","smaller","ocean","record","triangle","appearance","youth","neighborhood","finally","particles","page","level","fifty","television","entirely","language","support","if","directly","season","gather","cake","brought","divide","prove","bottle","trip","fine","board","bill","rate","stiff","blood","production","breathe","seed","child","cast","sheet","sense","army","airplane","public","composed","fun","related","pie","form","did","taste","upper","each","new","rose","feature","youth","make","roar","motion","teach","winter","measure","nice","entirely","using","treated","voyage","shallow","essential","phrase","except","sea","tiny","upward","volume","fighting","getting","dangerous","part","syllable","cotton","road","wife","engineer","public","sudden","chest","greatest","television","comfortable","brush","energy","street","case"
"arrow","plates","whistle","dish","understanding","finally","wheat","means","card","favorite","somewhere","strike","halfway","ship","accident","powder","sick","lying","arrow","dinner","rush","beautiful","various","instrument","entirely","there","star","pig","now","rear","swung","stuck","guide","what","cloud","president","table","hit","select","bread","weak","jungle","plates","tonight","hair","copy","cookies","continued","steady","team","made","enemy","facing","dish","distance","throughout","protection","badly","mark","lift","felt","tired","meat","pictured","storm","hunt","stage","sentence","kitchen","wherever","pack","hat","widely","original","themselves","percent","tribe","goose","simply","company","broad","bad","fastened","maybe","great","should","combination","band","related","pocket","completely","press","donkey","bone","if","grain","themselves","whatever"
"people","remember","east","nails","church","direct","tightly","bag","brown","planned","mainly","root","favorite","came","foreign","among","shoulder","corner","greatest","fed","thee","disease","step","chapter","beneath","recall","hung","longer","park","suppose","summer","gasoline","carbon","grass","electric","under","donkey","scientist","fierce","taken","ability","met","home","many","tone","syllable","took","born","particles","told","lady","repeat","finest","merely","military","pass","stronger","became","gather","nervous","lungs","ill","attempt","trade","thus","swimming","load","writing","anything","syllable","certain","grown","card","union","finest","aware","influence","putting","rocky","flat","guess","yourself","declared","compass","parts","slight","tight","written","east","take","library","highest","his","sent","extra","everything","become","fix"
"row","property","balloon","west","find","village","topic","learn","indicate","by","stream","service","army","slipped","lunch","chest","shore","continued","happy","slow","dinner","vegetable","show","establish","pictured","person","sweet","speak","creature","milk","deal","solve","selection","my","almost","began","duck","push","plenty","happened","question","factor","straight","connected","mud","frozen","felt","discussion","ought","group","happy","dot","close","higher","week","sweet","bottle","beside","alike","sure","president","increase","open","hurry","lack","potatoes","butter","mental","official","organization","jack","pick","love","fresh","orbit","today","hung","however","general","meant","leave","labor","becoming","coal","laugh","stronger","close","forest","piano","atom","school","piano","bright","take","shine","characteristic","kind","brought"
"most","begun","location","smooth","split","east","promised","principle","fine","got","ran","pure","command","probably","effort","influence","pay","degree","yourself","thought","aloud","opposite","numeral","wise","discovery","classroom","loose","offer","plan","meal","thread","percent","corn","attempt","season","flag","natural","station","whom","colony","caught","human","widely","pair","underline","basic","black","cloth","religious","valuable","ability","phrase","pole","tune","both","call","value","raw","bottle","went","night","beginning","element","there","till","dust","longer","show","hunter","nest","community","advice","object","you","station","frighten","union","soil","horn","sand","pass","grass","cake","climate","dull","concerned","donkey","engineer","ants","energy","stared","official","therefore","successful","her","level","bowl","heavy"
"basis","heavy","angry","full","natural","strip","climate","officer","sure","win","advice","produce","plane","board","power","jack","magic","direction","copper","directly","family","folks","help","produce","human","fun","beneath","fourth","grow","allow","stand","process","tune","fun","answer","name","completely","advice","tiny","element","cell","forest","medicine","tales","action","stand","most","organized","balance","seven","ordinary","electricity","exactly","hundred","behavior","fat","road","shirt","high","suggest","cry","usual","but","daughter","object","needle","tears","three","at","elephant","shout","stage","science","grown","indeed","effect","page","orange","someone","effort","beauty","fix","kitchen","chance","gently","matter","local","thumb","goose","donkey","blow","studying","experiment","hold","information","tie","every","increase"
"manufacturing","fix","rocky","setting","so","clock","tears","waste","page","stream","within","degree","nervous","heading","planning","bread","blank","industry","strong","obtain","figure","except","new","limited","travel","fight","account","struck","scientific","every","frighten","opportunity","source","unhappy","eventually","rabbit","arrange","clothes","swim","rather","found","length","coast","drink","stand","purpose","control","thousand","girl","forgot","soon","carbon","thousand","differ","leaf","dirty","disappear","period","press","parallel","pressure","show","thing","hide","fear","vast","verb","material","because","frog","fast","shore","orange","snake","leader","electricity","involved","middle","rocky","railroad","activity","had","article","honor","verb","across","stove","occur","indicate","very","flew","ten","contain","lion","warn","family","tales","hide"
"chart","grown","naturally","highway","silk","account","cry","consonant","everywhere","sunlight","automobile","strong","outline","quietly","rhyme","moving","health","many","round","explain","stand","loss","after","type","somehow","sky","tobacco","curious","positive","best","alone","pain","lay","dig","machine","potatoes","southern","drink","like","off","principal","warn","level","eleven","whatever","off","hall","himself","younger","open","cap","great","establish","zero","truth","leaf","heat","smoke","eight","our","waste","promised","lake","nearby","be","anyway","open","probably","test","eager","stand","baby","pair","browserling","forest","cold","train","popular","fell","close","mountain","tales","heavy","cabin","its","word","shout","floor","afraid","moon","pig","lay","solve","this","then","education","tall","new"
"chamber","lonely","ride","city","ancient","show","several","port","mean","doctor","practical","breakfast","loud","bit","excitement","throughout","distant","merely","second","essential","toward","arm","consider","active","example","butter","sink","shaking","interest","film","enough","alive","pack","reader","shallow","melted","spoken","transportation","suppose","pole","foreign","rubber","dull","sometime","dangerous","scientific","activity","total","those","fight","pole","wheat","lake","powder","generally","whispered","table","discovery","quiet","hit","limited","suggest","month","hand","pile","name","prepare","result","will","hang","factor","composition","yet","fruit","nearest","excellent","funny","shadow","run","captured","pick","settle","dead","fruit","helpful","careful","office","dug","hardly","are","charge","difference","skin","distance","at","judge","conversation","kept"
"sail","trunk","colony","produce","including","mistake","busy","car","situation","early","means","angry","parallel","memory","well","word","number","feathers","whenever","spent","reach","per","practical","related","note","experience","same","largest","leaf","provide","white","globe","apartment","problem","pleasant","field","hope","hide","section","recognize","twelve","talk","second","zero","double","noon","plan","spent","indicate","one","made","government","importance","drop","arrow","sign","coal","swimming","food","turn","future","frighten","occur","familiar","especially","rate","while","she","job","himself","complex","supper","studying","voice","song","silly","managed","ship","class","century","nervous","grew","journey","dull","dust","broke","struck","lake","mistake","highest","husband","disappear","physical","pure","dried","clock","rubbed","constantly"
"respect","carefully","valley","southern","be","what","song","powerful","sister","born","route","afraid","welcome","pleasure","bone","thumb","slowly","somewhere","dug","main","manner","find","light","before","he","classroom","silly","against","discussion","frozen","traffic","led","fruit","tie","found","bigger","sweet","fed","reason","claws","crack","center","fight","firm","open","mad","face","according","information","wish","atmosphere","aware","shot","occasionally","outline","finally","earlier","automobile","student","desk","hardly","more","however","sold","spread","led","especially","replied","review","using","are","vertical","instance","chair","skin","pleasant","am","machinery","organization","courage","single","caught","blind","piano","floor","depth","shop","guide","biggest","stream","heart","agree","opportunity","vowel","coach","operation","call","start"
"deer","trace","volume","scene","drew","lady","game","trade","straight","means","lamp","cake","electric","fewer","design","anyway","spider","struggle","seat","environment","dirt","spring","harbor","classroom","wild","meal","symbol","unit","rush","send","bicycle","active","stage","mouse","body","terrible","quite","browserling","half","fed","his","solution","manufacturing","pitch","path","hit","except","government","that","began","no","characteristic","treated","manner","chart","make","carry","evidence","stairs","pay","definition","everyone","breeze","exactly","car","greatly","ants","bend","hot","up","secret","fewer","mighty","aware","printed","fish","discover","tongue","your","pack","rice","library","doubt","national","political","tiny","thumb","fought","bean","somebody","are","temperature","equal","doubt","cross","average","chest","save"
"song","strip","carry","baseball","outline","flow","still","he","thus","young","getting","moon","class","movie","leave","teeth","sea","went","poetry","snake","greatest","coming","score","business","railroad","specific","well","thumb","copper","harder","farther","cool","eventually","triangle","give","strong","pair","stepped","consider","lunch","shore","herself","practice","rising","dig","call","industrial","quickly","hardly","quite","massage","excited","easily","meal","meet","kept","fifteen","language","wind","hospital","circle","musical","strike","fast","lift","gradually","danger","available","sound","iron","depth","powerful","needed","suppose","gently","basic","pure","exclaimed","manufacturing","gift","noise","loose","atomic","nearly","caught","sunlight","taught","country","purple","transportation","local","love","vertical","him","position","act","snake","room"
"fireplace","coming","element","explain","experience","copy","progress","dog","last","within","attention","listen","potatoes","belong","station","substance","clean","dull","cow","shop","dot","stopped","object","them","thick","leg","swung","depth","local","written","roar","do","tales","express","expect","something","cast","gate","food","crop","bridge","yourself","native","pink","count","met","arm","left","furniture","chamber","number","center","thirty","nor","refused","square","old","recognize","additional","newspaper","recognize","easily","voyage","arrive","hang","short","anywhere","square","above","fresh","opinion","herself","social","both","property","loose","tropical","halfway","stream","stone","beneath","highest","discovery","leave","friend","safe","straight","outline","expression","origin","ask","equally","his","heavy","fear","bound","war","write"
"seat","see","stronger","tank","relationship","sets","cookies","report","house","hay","simply","wide","colony","cabin","nodded","clock","southern","factor","combine","directly","shot","success","return","construction","atmosphere","related","stomach","however","parts","anything","captain","stairs","bank","draw","accurate","group","fellow","having","rush","compound","chart","season","father","near","angle","layers","write","design","rocket","ice","nodded","grass","fox","frog","husband","memory","stairs","star","dinner","tonight","public","music","brief","directly","season","solve","species","block","if","fifth","drink","range","tall","settlers","dear","come","contrast","ever","classroom","becoming","climb","recognize","breathing","series","speech","present","mean","personal","dollar","moment","lie","hold","at","war","film","total","went","nervous"
"report","driver","return","steam","until","basket","milk","fire","valuable","native","ran","split","southern","word","needle","thread","each","plate","we","previous","basket","sport","begun","thirty","shout","bound","needs","must","avoid","bet","honor","country","map","doing","keep","pair","basic","shallow","getting","carried","law","laid","major","sleep","too","keep","nothing","depth","leave","milk","wooden","symbol","forgotten","no","important","level","gain","capital","scale","program","drove","kids","main","attached","while","pure","fly","amount","chosen","paper","nose","onlinetools","speech","driving","was","purpose","gather","post","shallow","signal","driven","anywhere","design","hay","week","courage","under","ago","highest","fall","enemy","direction","plain","solution","religious","slept","beyond","love"
"point","fresh","relationship","rocket","due","in","offer","loose","helpful","tail","supply","that","nation","breathe","living","she","lucky","room","quick","grabbed","wore","sheep","frog","origin","die","of","track","gulf","mainly","flat","doing","but","buried","glad","visit","swept","lying","breathe","ball","traffic","telephone","numeral","circus","lying","sets","teeth","brother","as","political","atomic","till","mud","completely","jar","island","beside","section","southern","noon","cause","broad","manufacturing","look","shirt","eaten","pleasant","damage","hundred","bad","grandfather","tax","president","hurt","studied","evidence","wind","information","good","lips","went","thick","drew","large","respect","mostly","lot","aside","threw","drawn","curious","writing","long","farther","social","read","desert","visit","nails"
"cloth","copy","farther","live","repeat","brought","value","mirror","famous","kept","together","nearly","wool","official","cage","come","without","temperature","begun","pull","pocket","birth","stretch","broken","flower","feet","building","nature","improve","hearing","compare","police","me","phrase","real","try","dawn","opinion","behind","medicine","by","pressure","progress","period","our","discover","composed","capital","either","water","hunt","root","arrange","had","goes","vapor","low","breakfast","anywhere","yellow","length","look","trip","deer","fort","term","exact","cost","blind","prove","reason","stay","combine","plural","nose","feed","settlers","detail","machinery","type","production","spring","parallel","gravity","poet","end","chest","sat","high","belt","cloud","child","exactly","once","ability","tool","needed","greater"
"special","period","spirit","earlier","pull","careful","knew","pressure","finish","instance","everything","location","mile","sun","became","constantly","trap","origin","alphabet","silk","yes","prove","generally","rope","invented","scene","nest","concerned","say","deer","zero","sport","anyone","popular","chance","milk","loose","anywhere","vegetable","atmosphere","ball","unless","carefully","her","struggle","useful","leather","real","of","attack","party","throat","garden","recent","trick","broke","danger","ill","mainly","forward","replace","tropical","palace","exercise","steep","band","increase","mice","whenever","former","winter","dance","wet","swim","nose","hill","modern","blew","tomorrow","as","realize","material","on","continent","frame","suggest","forward","western","material","sister","game","solution","won","fewer","far","repeat","replace","tin"
"than","plastic","forgotten","yellow","sign","long","came","salmon","ought","chemical","became","floating","higher","molecular","disappear","due","him","asleep","motion","heavy","basic","earn","bone","somewhere","safe","speak","excellent","pale","blood","labor","treated","three","within","official","world","fresh","jump","instance","bowl","pot","rhyme","exchange","below","underline","trap","joy","plant","to","proper","college","measure","paragraph","lamp","your","fed","notice","mad","chosen","slowly","brought","front","strong","these","liquid","held","somewhere","everything","nearby","subject","hide","variety","excellent","bit","break","bigger","riding","simply","with","boy","then","whom","independent","rhythm","rush","shall","hung","gravity","gulf","customs","type","promised","those","drew","film","sentence","together","sold","without"
"whenever","eat","as","sad","would","sheep","percent","nails","slide","attached","tiny","mark","exact","noun","spend","research","shelf","rush","death","fairly","observe","worse","compass","science","boat","comfortable","empty","sleep","earth","cry","nervous","grabbed","his","grain","bush","recent","stood","across","parts","small","herd","themselves","look","bar","toward","wise","movement","please","glass","married","lay","function","why","kind","respect","planning","stuck","window","were","gravity","nor","remarkable","neck","stand","shoot","anyone","command","plate","gone","dress","pig","southern","travel","anyway","pain","mail","atmosphere","silent","terrible","noun","failed","examine","cow","nice","species","current","north","bound","sky","how","choice","memory","next","month","consonant","coal","dry","whole"
"audience","differ","attached","atmosphere","bit","against","board","mail","river","mood","many","sort","learn","speech","it","canal","driven","average","few","experience","gradually","asleep","meant","such","built","something","coat","state","outline","shape","sport","either","steam","circle","swept","nation","bound","catch","hit","strong","steam","but","magic","fierce","so","yellow","story","root","birds","tower","giant","mind","we","prevent","she","vowel","build","movie","dollar","universe","plural","stay","selection","upper","lovely","allow","many","fell","here","differ","wear","belong","nuts","clothes","track","trunk","volume","excellent","alike","include","wheat","whether","seeing","bowl","appropriate","likely","feathers","drink","hard","tight","goose","shake","television","weigh","peace","shelter","thus","cloth"
"solve","freedom","discuss","hospital","pond","number","weak","private","death","go","heart","ill","dead","finish","harder","drew","mean","kept","strange","percent","wire","replace","us","country","notice","thrown","cutting","circle","mile","movement","row","level","kept","bean","becoming","central","yesterday","frame","industrial","accurate","sentence","child","who","hall","additional","weight","bad","loud","maybe","desk","worth","twice","built","hill","paid","camp","stove","solve","atom","score","production","whatever","but","mistake","only","result","journey","body","dear","victory","fought","finish","combination","suppose","sides","earn","strike","diagram","beat","distance","railroad","palace","swimming","behavior","mainly","command","then","firm","rocket","skin","rapidly","shot","simplest","memory","winter","perfectly","angle","tobacco"
"copy","notice","when","whatever","guard","house","promised","young","becoming","sight","month","bell","three","native","period","lunch","grow","smoke","silence","adjective","wet","choose","joined","more","cap","box","ball","halfway","church","powerful","desk","hat","burn","chart","rhythm","spring","throughout","youth","difference","speak","negative","factor","tobacco","mountain","division","compare","mostly","round","sit","stood","glass","pretty","copy","enter","shelter","built","folks","somewhere","quickly","copy","belt","done","swim","attack","tower","flew","cover","lie","low","trail","had","aside","history","built","happened","donkey","victory","traffic","tall","knife","part","soon","environment","baseball","yellow","color","long","many","customs","exclaimed","shorter","home","stepped","popular","season","hay","full","zoo"
"pack","hung","increase","real","box","outer","underline","minute","dig","although","visitor","character","means","oil","usual","tropical","act","steel","square","badly","this","taught","conversation","grabbed","freedom","degree","whom","main","wagon","met","shoulder","create","aid","use","dinner","examine","distance","stepped","word","in","actual","sweet","herself","needed","eight","among","watch","coast","additional","book","fresh","direction","through","team","ground","flower","its","everybody","firm","origin","object","wrapped","discuss","image","meet","single","gather","independent","fox","flew","particles","let","when","locate","teacher","against","service","valuable","greater","worker","outer","porch","doll","route","occur","clearly","whom","also","series","waste","have","piano","lunch","lesson","breeze","ride","pole","stay"
"parent","piece","verb","bridge","lungs","star","order","western","beauty","corner","together","foot","copper","cream","lake","struggle","sign","dangerous","subject","question","operation","school","organized","supper","audience","bend","best","height","left","thousand","clear","using","older","arrangement","angry","partly","cloth","moving","courage","degree","remarkable","while","stomach","balance","sentence","break","bread","low","curve","contain","southern","left","herself","wore","valuable","lesson","aid","paid","usual","industry","vast","laugh","well","object","somehow","probably","luck","put","column","lovely","available","rays","visit","funny","time","women","something","gun","toward","mass","imagine","out","largest","being","something","government","view","impossible","creature","essential","gift","next","lack","anywhere","storm","beat","equal","crack"
"task","look","arrive","clothing","suggest","process","brief","principal","purple","note","nervous","straight","number","prepare","swam","hide","air","full","excellent","ability","thee","shelf","nothing","settlers","swing","lips","larger","question","author","two","design","husband","lack","anyway","greater","cross","door","related","rain","thus","youth","alive","fighting","look","fallen","friend","make","sat","title","safety","hearing","not","down","were","birthday","with","article","limited","period","twenty","wind","fifth","white","rod","range","bow","consist","longer","tower","copy","church","directly","growth","life","stop","hello","basis","due","shake","stop","will","real","disappear","moon","oxygen","mill","chamber","height","reason","mountain","seems","fence","border","important","boat","raw","among","mouth"
"research","mental","shadow","accurate","stared","rain","last","grandfather","apart","refer","wrapped","greater","onto","needle","said","because","leave","prove","soil","rain","blood","skill","mass","art","bicycle","work","five","shake","master","brick","sort","rise","high","opportunity","missing","mean","future","bee","movie","empty","stepped","torn","memory","mistake","sugar","income","strip","wood","this","tales","kids","hot","night","hung","vegetable","there","result","deeply","announced","cotton","addition","rubber","mistake","over","research","label","supper","noise","usual","object","judge","supply","law","mail","typical","lying","composed","solve","shoe","behind","least","church","wall","family","brick","tape","slabs","lesson","barn","relationship","talk","afternoon","riding","yet","possibly","desert","spite","harder"
"ring","bush","guide","west","however","layers","thank","step","those","street","develop","possible","shelf","rush","porch","proud","equator","air","location","spend","monkey","division","instant","street","have","getting","get","salt","motor","travel","married","do","machinery","saddle","nearest","belong","himself","price","eye","thing","troops","society","aloud","pie","bite","troops","perfectly","blue","concerned","shirt","flag","poet","mountain","flew","foot","until","swam","short","stand","year","former","lose","battle","promised","harder","recent","herself","gave","suggest","idea","mouth","decide","today","complete","musical","explain","slept","loss","wolf","pattern","powder","sight","never","composed","no","making","dear","between","scale","able","perfect","just","rubber","country","son","sand","press","fall"
"attention","fly","voyage","rear","throw","somehow","slowly","smooth","police","mass","saddle","bright","told","fed","child","region","hidden","here","pipe","layers","cap","neighborhood","but","automobile","country","baby","grew","twelve","gentle","clothing","this","sing","store","tears","island","contrast","discover","stone","everywhere","team","cabin","second","stock","girl","river","brave","sheep","vessels","skill","solar","everything","answer","market","here","bet","forth","managed","married","double","seems","crew","drop","lie","value","fought","choose","ever","teacher","monkey","circus","say","fastened","chose","pig","free","neighbor","trace","bowl","fat","crop","fine","level","know","fix","fox","whatever","gave","tiny","wait","stock","younger","fuel","mirror","eleven","fell","mouse","bank","shake"
"rush","lion","general","storm","frozen","name","substance","swam","firm","offer","likely","recently","snake","forty","same","tried","heavy","voice","whose","bet","instance","correctly","topic","belt","successful","actual","lonely","naturally","return","hearing","off","press","fog","able","expression","fallen","physical","row","struggle","interior","army","course","jar","activity","before","moment","ground","visitor","taken","victory","tomorrow","whom","pitch","deeply","becoming","shadow","suddenly","wonderful","everybody","dangerous","draw","coast","heat","swing","subject","plural","creature","across","headed","got","putting","ring","upper","mark","to","tide","blank","chance","success","halfway","size","interior","discuss","dig","post","street","equal","concerned","thread","personal","wheat","someone","truth","lips","chamber","square","recently","active"
"cast","outside","temperature","stop","generally","roof","problem","chair","faster","indeed","somehow","group","spin","lie","dozen","correctly","sit","production","not","fort","sick","friend","heard","trade","worse","means","badly","those","system","shoulder","handle","jar","building","today","weak","sort","bear","machinery","most","important","library","mice","vapor","dig","want","claws","crowd","indicate","program","street","voyage","man","limited","yard","furniture","slave","farm","voyage","same","home","driven","planning","solid","plate","list","six","continent","play","symbol","rubbed","plain","success","brain","figure","glad","silver","sleep","summer","hand","twenty","everyone","beauty","student","gulf","stepped","tropical","halfway","yellow","mission","loud","liquid","age","twenty","friend","mountain","both","support","dozen"
"return","cabin","gather","between","advice","year","gain","wet","aware","he","gate","arrow","food","cheese","means","support","month","where","halfway","outer","city","thirty","chamber","invented","engine","massage","compare","necessary","ride","cause","break","second","ask","explain","alone","she","face","higher","built","fall","planned","mix","idea","was","kitchen","plain","sat","fifteen","raw","into","depend","stretch","hang","shadow","movement","depth","crowd","involved","pencil","improve","somehow","sitting","replace","eleven","motor","corn","mother","easier","supply","ground","welcome","ordinary","region","purple","border","branch","bat","bush","group","ranch","play","exciting","fourth","life","greater","crack","prevent","cage","tight","each","add","then","plan","dropped","picture","baby","harbor","nose"
"finally","birth","trap","available","closer","pond","daily","task","anybody","similar","hello","discussion","lady","date","birthday","win","steep","using","second","before","lose","funny","time","original","before","cost","hospital","last","connected","answer","price","root","seems","one","airplane","decide","connected","equal","parent","something","usually","mighty","include","pig","wet","inch","deeply","bend","exist","space","thee","accept","throw","room","add","soil","percent","major","say","plenty","poet","night","sheet","information","hope","crack","program","coffee","from","put","let","taught","society","living","lower","slabs","adjective","dream","wash","hair","cause","elephant","think","scene","cross","safe","locate","jack","discuss","fox","mother","political","prove","massage","ranch","muscle","fruit","tone"
"aside","tide","aboard","decide","equally","dirt","happened","pay","shorter","success","halfway","has","sweet","silk","book","donkey","later","dangerous","service","disease","duty","base","apartment","become","cry","apartment","plus","want","became","will","paragraph","straw","prove","free","fair","let","tent","only","mail","chemical","such","herd","purpose","form","vertical","pole","correct","tape","record","teeth","visit","nobody","main","wrote","policeman","sometime","belt","sat","dangerous","bush","explanation","solve","determine","oxygen","circus","pure","zoo","faster","aware","fur","direct","mood","research","solution","adventure","start","basket","she","pie","safety","slipped","touch","pocket","add","characteristic","satisfied","faster","condition","time","manufacturing","screen","lot","further","give","certainly","airplane","plant","pound"
"wore","result","beauty","engineer","sound","course","list","letter","stronger","street","leather","cookies","opposite","star","chart","order","poet","property","sink","brown","angle","kids","mine","throat","entire","leaf","mind","couple","control","major","box","hand","paper","order","solar","gather","bone","trace","fifth","sent","bow","barn","fresh","pretty","evidence","tomorrow","wing","mail","gave","railroad","film","electricity","these","excitement","shelter","gentle","probably","flag","alike","simple","journey","do","fighting","health","lovely","common","team","mean","measure","building","waste","pet","recently","spite","chair","individual","fill","prize","means","rather","positive","explain","develop","worker","reach","melted","half","end","hot","entirely","roll","only","plates","cook","arrangement","shallow","think","quick"
"should","gain","push","noun","division","upper","silly","correctly","magic","drive","former","hard","fair","inch","fuel","good","cost","interior","seldom","different","however","plus","treated","secret","potatoes","frame","develop","basket","plural","spring","upon","thee","cell","underline","hour","forget","from","sale","class","plastic","parts","next","whistle","limited","red","poet","left","wheel","teach","verb","individual","copy","middle","butter","small","silly","against","impossible","sold","safety","improve","tin","capital","deep","fairly","rush","part","yard","bark","do","cook","seat","handle","station","past","sign","card","mother","monkey","creature","rose","six","fair","are","minerals","you","earlier","such","account","complete","open","whenever","tongue","send","soldier","mission","family","buried"
"successful","political","protection","well","check","which","bet","discussion","east","evening","grandmother","lay","gather","sad","village","nearby","tube","rough","eat","repeat","went","team","someone","rice","slave","weigh","except","its","passage","halfway","needle","north","period","put","browserling","even","type","steep","burn","course","slave","found","wagon","brought","east","age","flow","else","each","movie","elephant","cotton","torn","help","paint","powder","produce","indicate","equator","trip","attached","dull","rubbed","can","pale","hospital","arrive","machine","feet","pride","glad","support","birth","thirty","small","hour","board","constantly","require","worker","hat","ahead","brother","collect","breakfast","note","drew","began","count","exact","slept","state","tower","experiment","importance","our","single","gentle"
"jack","power","search","graph","meat","sign","already","black","globe","foreign","human","habit","meet","model","process","calm","cattle","dinner","able","spring","rubbed","smile","person","port","several","average","mixture","package","sharp","difficult","chapter","mother","flies","social","plastic","everything","feed","captain","explanation","oldest","enjoy","constantly","run","cent","escape","body","thee","related","afraid","pot","cow","stiff","past","idea","although","strength","full","coffee","hunt","company","largest","ring","finest","studying","down","tape","pour","spend","many","quickly","real","section","curious","electricity","evidence","village","weight","yesterday","weak","throat","total","locate","over","country","iron","nails","low","fire","map","list","excitement","wealth","double","what","sitting","largest","cage","seven"
"needed","soap","may","eye","choose","gift","clearly","four","modern","sets","jump","dried","order","differ","gradually","slipped","army","chapter","excellent","enough","personal","steep","duty","outline","uncle","movement","surface","pack","settle","fifty","threw","happily","cut","clock","unusual","mark","your","product","arrangement","facing","crack","vapor","addition","folks","wild","dry","progress","wherever","brave","quickly","us","comfortable","thank","score","transportation","laugh","corn","average","movement","process","safe","price","table","shaking","shape","stranger","yellow","broke","observe","decide","missing","blew","function","growth","went","silver","one","statement","step","useful","primitive","prove","win","join","important","lot","silk","circus","depth","thread","planned","degree","ready","chapter","castle","famous","positive","chapter"
"particular","accurate","world","but","cent","related","excited","grandmother","score","obtain","day","manufacturing","hour","interest","leaf","pipe","shirt","flag","breath","become","major","information","early","rain","fix","fun","price","powder","man","route","compare","prove","hundred","according","exclaimed","bite","eight","automobile","money","perhaps","swing","run","wife","wooden","equal","mill","nails","entirely","colony","mail","could","pair","first","tobacco","mass","struck","living","gentle","near","complex","forty","every","softly","way","rod","allow","whom","port","pilot","stopped","themselves","per","library","to","wonder","look","gain","threw","noun","they","difficult","word","cell","rising","actual","voice","solve","how","arrive","actually","rhythm","to","clothes","girl","mother","past","two","film"
"eight","smell","slipped","local","proper","anyway","mixture","official","discussion","then","ball","stand","game","excitement","calm","collect","hungry","till","harder","locate","human","poet","liquid","serious","biggest","darkness","origin","worried","remember","change","cattle","seems","cattle","sort","unhappy","vessels","else","planned","cool","explore","off","won","some","suppose","half","second","been","coming","known","government","composed","organized","hang","ourselves","instrument","bush","cost","sound","some","loud","motion","happen","heard","yes","across","road","mathematics","tropical","various","blow","weak","man","oxygen","rubbed","property","memory","joy","voice","deal","should","opposite","mysterious","construction","wheat","dark","captain","find","highway","fill","roll","push","hair","surface","bad","species","power","general","breakfast"]        
        await ctx.send(f'the {random.choice(responses)} craft')

client.run('')                    
